import { AuthCard, AuthLink } from '../components/auth-card';
import { TwoFactorForm } from './two-factor-form';

export const metadata = {
  title: 'Two-step verification',
};

export default function TwoFactorPage() {
  return (
    <AuthCard
      title="Two-step verification"
      description="Enter the 6-character code generated by your authenticator app."
      footer={
        <>
          Having trouble signing in?{' '}
          <AuthLink href="/auth/login" label="Back to login" />
        </>
      }
    >
      <TwoFactorForm />
    </AuthCard>
  );
}
